use_frameworks!

platform :ios, '9.0'

target 'MCSWechat_Example' do
  pod 'MCSWechat', :path => '../'

  target 'MCSWechat_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
